version: '3' 

volumes:     
    pgdata:

services:
    python:
        build: 
            context: .
            dockerfile: Dockerfile
        volumes:
            -  ./enoki:/enoki
        ports: 
            - 8000:8000
        depends_on: 
            - enoki_db

    enoki_db:
        image: postgres
        environment:
            POSTGRES_USER: enoki
            POSTGRES_PASSWORD: enoki
            POSTGRES_DB: enoki_db
        volumes: 
            - pgdata:/var/lib/postgresql/data
        ports: 
            - "5435:5432"

    pdadmin_compose:
        image: dpage/pgadmin4
        environment: 
            PGADMIN_DEFAULT_EMAIL: "enoki@hotmail.fr"
            PGADMIN_DEFAULT_PASSWORD: "enoki"
        ports:
            - "16543:80"
        depends_on: 
            - enoki_db